name: valuedebate
channels:
  - defaults
dependencies:
  - pip=25.0
  - python=3.12.9
  - pip:
      - datasets==3.5.0
      - jsonlines==4.0.0
      - matplotlib==3.10.1
      - numpy==2.2.5
      - openai==1.76.0
      - PyYAML==6.0.2
      - ray==2.44.1
      - Requests==2.32.3
      - scikit_learn==1.6.1
      - sentence_transformers==4.1.0
      - tenacity==9.1.2
      - torch==2.7.0
      - tqdm==4.66.5
